### ISSUE TITLE
pagina nao encontrada

### ISSUE THREAD

**Issue by joao-omati** [joao-omati/projeto-integrador#14]
quando se clica em atualizar registro e deletar registro aparece 
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by EzioPP** [comment]
isso é devido ao tipo de request que é GET, no caso passa o parametro de id dentro da pagina de resultados no get
exemplo http://127.0.0.1:5000/atualizar/1 <- id 
quando vc acessa diretamente acaba indo pra http://127.0.0.1:5000/atualizar/{{resultado[1]}} q n existe
